---
- name: (APACHE) Install Apache Web server and PHP-FPM
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php-fpm
    - php-mysql
    - php-pear
    - php-cgi
    - ufw
  when: ansible_os_family == "Debian"

- name: (APACHE) Remove the default Websites
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload apache

- name: (APACHE) DEBUG - Allow RSYNC for new super user without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^%sudo'
    line: "{{ ansible_user }} ALL=NOPASSWD: /usr/bin/rsync"
  changed_when: false

- name: (APACHE) Copy some template for Web servers
  synchronize:
    src: files/apache_templates/
    dest: /root/
    links: yes
    recursive: yes

- name: (APACHE) DEBUG - Disallow RSYNC for new super user without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: absent
    insertafter: '^%sudo'
    line: "{{ ansible_user }} ALL=NOPASSWD: /usr/bin/rsync"
  changed_when: false

- name: (APACHE) Copy the Diffie-Hellmann parameters
  copy:
    src: dhparams.pem
    dest: /etc/ssl/dhparams.pem
    owner: root
    group: root
    mode: 0644

- name: (APACHE) Check enabled modules
  stat:
    path: /etc/apache2/mods-enabled/{{ item }}
  with_items:
    - ssl.load
    - actions.load
    - proxy_fcgi.load
    - env.load
    - rewrite.load
    - headers.load
  register: modules

- name: (APACHE) Enable missing modules
  command: a2enmod {{ item.item }}
  with_items: "{{ modules.results }}"
  notify: restart apache
  when: not item.stat.exists

- name: (APACHE) Open the HTTP port on the firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp
    direction: in
  notify: reload ufw

- name: (APACHE) Open the HTTPS port on the firewall
  ufw:
    rule: allow
    port: 443
    proto: tcp
    direction: in
  notify: reload ufw

- name: (USERSKEL) DEBUG - Allow RSYNC for new super user without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^%sudo'
    line: "{{ ansible_user }} ALL=NOPASSWD: /usr/bin/rsync"
  changed_when: false

- name: (USERSKEL) Copy the user's skeleton template for Web servers
  synchronize:
    src: files/user_skel/
    dest: /etc/skel/
    links: yes
    recursive: yes

- name: (USERSKEL) DEBUG - Disallow RSYNC for new super user without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: absent
    insertafter: '^%sudo'
    line: "{{ ansible_user }} ALL=NOPASSWD: /usr/bin/rsync"
  changed_when: false
