---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload ufw
  service:
    name: ufw
    state: restarted

- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart apache
  service:
    name: apache2
    state: restarted
